version: "3"
services:
  es01:
    build: .
    container_name: es01
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

    # kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200

    #mysql
  mysql:
    platform: linux/arm64/v8
    image: mysql:8.0.33
    container_name: backend-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: Password123
    restart: always
    networks:
      - mysql-network
    command: --default-authentication-plugin=mysql_native_password

  cli:
    image: mysql:8.0.33
    networks:
      - mysql-network
    command: mysql -hmysql -uuser -ppassword db

networks:
  mysql-network:
    driver: bridge