package com.elasticsearch.demo.repository.model;

public class AppUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.id
     *
     * @mbg.generated Thu Aug 17 09:27:08 JST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.login_password
     *
     * @mbg.generated Thu Aug 17 09:27:08 JST 2023
     */
    private String loginPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.id
     *
     * @return the value of app_user.id
     *
     * @mbg.generated Thu Aug 17 09:27:08 JST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.id
     *
     * @param id the value for app_user.id
     *
     * @mbg.generated Thu Aug 17 09:27:08 JST 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.login_password
     *
     * @return the value of app_user.login_password
     *
     * @mbg.generated Thu Aug 17 09:27:08 JST 2023
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.login_password
     *
     * @param loginPassword the value for app_user.login_password
     *
     * @mbg.generated Thu Aug 17 09:27:08 JST 2023
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }
}